### ISSUE TITLE
Creation of Hero Section

### ISSUE THREAD

**Issue by Noxaelum** [MAKIENAUT/WMA-4.0-nextjs#17]

**Comment by Noxaelum** [comment]
Prod ticket link: https://github.com/users/MAKIENAUT/projects/2/views/1?pane=issue&itemId=86701744&issue=MAKIENAUT%7CWMA-4.0-nextjs%7C8

**Comment by Noxaelum** [comment]
PR link: https://github.com/MAKIENAUT/WMA-4.0-nextjs/pull/18

**Comment by Noxaelum** [comment]
@MAKIENAUT Kindly validate

**Comment by MAKIENAUT** [comment]
Under validation 👀
