### ISSUE TITLE
Creation of statement section

### ISSUE THREAD

**Issue by Noxaelum** [MAKIENAUT/WMA-4.0-nextjs#21]

**Comment by Noxaelum** [comment]
prod link: https://github.com/users/MAKIENAUT/projects/2/views/1?pane=issue&itemId=86702592&issue=MAKIENAUT%7CWMA-4.0-nextjs%7C10

**Comment by Noxaelum** [comment]
PR: https://github.com/MAKIENAUT/WMA-4.0-nextjs/pull/23

@MAKIENAUT kindly validate

**Comment by MAKIENAUT** [comment]
Reviewing 👀...
