### ISSUE TITLE
[PAGE] Services: Creation of Services Page

### ISSUE THREAD

**Issue by MAKIENAUT** [MAKIENAUT/WMA-4.0-nextjs#24]
Create Services Page (Derived from the Services Template's reusable component)

![Image](https://github.com/user-attachments/assets/bf200a89-51d0-4cb7-a7f3-34e56c145a17)

**Comment by MAKIENAUT** [comment]
Hello, @arvndcrz Please Validate!

**Comment by arvndcrz** [comment]
Moving this back to Backlogs for clarifications/changes.

**Comment by MAKIENAUT** [comment]
This changes will reflect once changes in the Platform Product Ticket #9 is finished...

**Comment by MAKIENAUT** [comment]
I have added the individual pages and fixed the issues of this product ticket in here: #39 

Please verify...

I will now move this to "To validate"

**Comment by arvndcrz** [comment]
This is reviewed and will be closing the ticket
