### ISSUE TITLE
Creation of Navbar

### ISSUE THREAD

**Issue by arvndcrz** [MAKIENAUT/WMA-4.0-nextjs#7]
Must Contain the following:

- **WMA Logo** (Links to homepage)
- **News** (Links to News page)
- **About us** (Links to About us page)
- **Services** (Links to Services page)

**Comment by Noxaelum** [comment]
[Dev link](https://github.com/users/MAKIENAUT/projects/2/views/1?pane=issue&itemId=87014912&issue=MAKIENAUT%7CWMA-4.0-nextjs%7C12)

**Comment by arvndcrz** [comment]
This product ticket is reviewed, all is well
