### ISSUE TITLE
Creation of the SERVICE SECTION --- Homepage

### ISSUE THREAD

**Issue by arvndcrz** [MAKIENAUT/WMA-4.0-nextjs#9]
Includes the different services offered:

- [ ] **Study and Exchange** w/ the assigned description and Learn More button
- [x] **Family Based** w/ the assigned description and Learn More button
- [x] **Temporary Employment**  w/ the assigned description and Learn More button

**Comment by MAKIENAUT** [comment]
Hello, @arvndcrz Please Validate!

**Comment by arvndcrz** [comment]
With the reference to the Services Template, it seems that description for the Student and Exchange card is shortened.
@MAKIENAUT Images below shows the difference:

Template:
![Image](https://github.com/user-attachments/assets/ead8b388-84f5-4665-a5f3-fd5133e1588b)


Website:
![Image](https://github.com/user-attachments/assets/3e838e91-0160-4656-9331-f8e24f9d99be)

**Comment by arvndcrz** [comment]
Moving this back to Backlogs for clarifications/changes.

**Comment by MAKIENAUT** [comment]
This is acknowledged... Putting it back to active, will address the issue...

**Comment by arvndcrz** [comment]
Change has been fixed, closing this ticket
